-- CreateTable
CREATE TABLE "Bairro" (
    "cd_bairro" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "ds_bairro" TEXT NOT NULL,
    "cd_cidade" TEXT,
    "cd_setor" TEXT,
    "ds_bairro_tribuna" TEXT,
    CONSTRAINT "Bairro_cd_cidade_fkey" FOREIGN KEY ("cd_cidade") REFERENCES "Cidade" ("cd_cidade") ON DELETE NO ACTION ON UPDATE NO ACTION
);

-- CreateTable
CREATE TABLE "Cidade" (
    "cd_cidade" TEXT NOT NULL PRIMARY KEY,
    "ds_cidade" TEXT NOT NULL,
    "uf_cidade" TEXT,
    "cidade_natal" TEXT
);

-- CreateTable
CREATE TABLE "CORREIOS_ONLINE" (
    "cep_numero" TEXT NOT NULL PRIMARY KEY,
    "tipo_descricao" TEXT NOT NULL,
    "logradouro_descricao" TEXT NOT NULL,
    "chave_bairro" DECIMAL NOT NULL,
    "bairro_descricao" TEXT NOT NULL,
    "chave_cidade" DECIMAL NOT NULL,
    "cidade_descricao" TEXT NOT NULL,
    "uf_sigla" TEXT NOT NULL,
    "data_atualizacao" DATETIME,
    "trecho_paridade" TEXT,
    "cd_titulo_logradouro" TEXT,
    "cd_tipo_logradouro" TEXT,
    "cd_cidade" TEXT,
    "cd_bairro" INTEGER
);

-- CreateTable
CREATE TABLE "ESCOLARIDADE" (
    "cd_escolaridade" DECIMAL NOT NULL PRIMARY KEY,
    "ds_escolaridade" TEXT
);

-- CreateTable
CREATE TABLE "Estado_Civil" (
    "cd_estado_civil" TEXT NOT NULL PRIMARY KEY,
    "ds_estado_civil" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "Formulario_Pessoa" (
    "cgc_pessoa" TEXT NOT NULL PRIMARY KEY,
    "dt_cadastro_pessoa" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "nm_pessoa" TEXT,
    "nm_fantasia_pessoa" TEXT,
    "rg_pessoa" TEXT,
    "cd_expedidor_pessoa" TEXT,
    "ds_naturalidade_pessoa" TEXT,
    "dt_nascimento_pessoa" DATETIME,
    "ie_pessoa" TEXT,
    "cd_estado_civil_pessoa" TEXT,
    "im_pessoa" TEXT,
    "cd_profissao_pessoa" DECIMAL,
    "end_pessoa" TEXT,
    "cd_bairro_pessoa" INTEGER,
    "nu_endereco_pessoa" TEXT,
    "cep_pessoa" TEXT,
    "end_complemento_pessoa" TEXT,
    "cd_cidade_pessoa" TEXT,
    "cd_tipo_logradouro_pessoa" TEXT,
    "nu_fone_pessoa" TEXT,
    "nm_conjuge" TEXT,
    "cd_profissao_conjuge" TEXT,
    "cd_expedidor_conjuge" TEXT,
    "nu_celular_pessoa" TEXT,
    "cic_conjuge" TEXT,
    "rg_conjuge" TEXT,
    "dt_nascimento_conjuge" DATETIME,
    "nu_caixa_postal_pessoa" TEXT,
    "tipo_pessoa" TEXT,
    "e_mail_pessoa" TEXT,
    "nm_contato" TEXT,
    "dt_nascimento_contato" DATETIME,
    "end_cobranca" TEXT,
    "nu_endereco_cobranca" TEXT,
    "end_complemento_cobranca" TEXT,
    "cd_bairro_cobranca" TEXT,
    "ds_bairro_cobranca" TEXT,
    "cd_tipo_logradouro_cobranca" TEXT,
    "cd_cidade_cobranca" TEXT,
    "ds_cidade_cobranca" TEXT,
    "uf_cobranca" TEXT,
    "cep_cobranca" TEXT,
    "nu_caixa_postal_cobranca" TEXT,
    "obs_pessoa" TEXT,
    "cd_escolaridade" DECIMAL,
    "sexo" TEXT,
    "vlr_salario" DECIMAL,
    "e_mail_extrato" TEXT,
    "nu_fone_zap" DECIMAL,
    "matricula_afiancado_imovel" TEXT,
    "end_imovel_afiancado" TEXT,
    "cd_cidade_afiancado" INTEGER,
    "nm_contato_fiador" TEXT,
    "nu_fone_contato_fiador" TEXT,
    "nu_fone_comercial_fiador" TEXT,
    "cd_bairro_fiador" INTEGER,
    "cd_bairro_trabalho" INTEGER,
    "cd_bairro_trabalho_conjugue" INTEGER,
    "cd_bairro_trabalho_conjugue_fiador" INTEGER,
    "cd_bairro_trabalho_fiador" INTEGER,
    "cd_cidade_fiador" TEXT,
    "cd_cidade_trabalho" TEXT,
    "cd_cidade_trabalho_conjugue" TEXT,
    "cd_cidade_trabalho_conjugue_fiador" TEXT,
    "cd_cidade_trabalho_fiador" TEXT,
    "cd_escolaridade_fiador" DECIMAL,
    "cd_estado_civil_fiador" TEXT,
    "cd_expedidor_conjuge_fiador" TEXT,
    "cd_expedidor_fiador" TEXT,
    "cd_profissao_conjuge_fiador" TEXT,
    "cd_profissao_fiador" DECIMAL,
    "cd_tipo_logradouro_fiador" TEXT,
    "cep_fiador" TEXT,
    "cep_trabalho" TEXT,
    "cep_trabalho_conjugue" TEXT,
    "cep_trabalho_conjugue_fiador" TEXT,
    "cep_trabalho_fiador" TEXT,
    "cic_conjuge_fiador" TEXT,
    "cis_fiador" TEXT NOT NULL,
    "ds_admissao" DATETIME,
    "ds_admissao_conjugue" DATETIME,
    "ds_admissao_conjugue_fiador" DATETIME,
    "ds_admissao_fiador" DATETIME,
    "ds_filicao_mae_conjuge" TEXT,
    "ds_filicao_mae_conjuge_fiador" TEXT,
    "ds_filicao_mae_fiador" TEXT,
    "ds_filicao_mae_pessoa" TEXT,
    "ds_filicao_pai_conjuge" TEXT,
    "ds_filicao_pai_conjuge_fiador" TEXT,
    "ds_filicao_pai_fiador" TEXT,
    "ds_filicao_pai_pessoa" TEXT,
    "ds_local_trabalho" TEXT,
    "ds_local_trabalho_conjugue" TEXT,
    "ds_local_trabalho_conjugue_fiador" TEXT,
    "ds_local_trabalho_fiador" TEXT,
    "ds_naturalidade_conjuge" TEXT,
    "ds_naturalidade_conjuge_fiador" TEXT,
    "ds_naturalidade_fiador" TEXT,
    "ds_pessoas_qi_morar" TEXT,
    "dt_cadastro_fiador" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "dt_nascimento_conjuge_fiador" DATETIME,
    "dt_nascimento_fiador" DATETIME,
    "e_mail_conjugue" TEXT,
    "e_mail_conjugue_fiador" TEXT,
    "e_mail_fiador" TEXT,
    "end_complemento_fiador" TEXT,
    "end_contato" TEXT,
    "end_contato_pr_fiador" TEXT,
    "end_contato_sg" TEXT,
    "end_contato_sg_fiador" TEXT,
    "end_fiador" TEXT,
    "end_trabalho" TEXT,
    "end_trabalho_conjugue" TEXT,
    "end_trabalho_conjugue_fiador" TEXT,
    "end_trabalho_fiador" TEXT,
    "ie_fiador" TEXT,
    "im_fiador" TEXT,
    "nm_adultos" INTEGER,
    "nm_conjuge_fiador" TEXT,
    "nm_contato_pr_fiador" TEXT,
    "nm_contato_sg" TEXT,
    "nm_contato_sg_fiador" TEXT,
    "nm_criancas" INTEGER,
    "nm_fantasia_fiador" TEXT,
    "nm_fiador" TEXT,
    "nm_pessoas" INTEGER,
    "nu_celular_conjuge" TEXT,
    "nu_celular_conjuge_fiador" TEXT,
    "nu_celular_fiador" TEXT,
    "nu_endereco_fiador" TEXT,
    "nu_endereco_trabalho" TEXT,
    "nu_endereco_trabalho_conjugue" TEXT,
    "nu_endereco_trabalho_conjugue_fiador" TEXT,
    "nu_endereco_trabalho_fiador" TEXT,
    "nu_fone_contato" TEXT,
    "nu_fone_contato_pr_fiador" TEXT,
    "nu_fone_contato_sg" TEXT,
    "nu_fone_contato_sg_fiador" TEXT,
    "nu_fone_fiador" TEXT,
    "nu_fone_trabalho" TEXT,
    "nu_fone_trabalho_conjugue" TEXT,
    "nu_fone_trabalho_conjugue_fiador" TEXT,
    "nu_fone_trabalho_fiador" TEXT,
    "nu_fone_zap_fiador" DECIMAL,
    "num_animais" INTEGER,
    "obs_fiador" TEXT,
    "rg_conjuge_fiador" TEXT,
    "rg_fiador" TEXT,
    "tipo_fiador" TEXT,
    "vlr_salario_conjuge" DECIMAL,
    "vlr_salario_conjuge_fiador" DECIMAL,
    "vlr_salario_fiador" DECIMAL,
    "banco" TEXT,
    "cd_bairro_fiador_one" INTEGER,
    "cd_bairro_fiador_two" INTEGER,
    "cd_cidade_fiador_one" TEXT,
    "cd_cidade_fiador_two" TEXT,
    "cd_escolaridade_fiador_one" DECIMAL,
    "cd_escolaridade_fiador_two" DECIMAL,
    "cd_estado_civil_fiador_one" TEXT,
    "cd_estado_civil_fiador_two" TEXT,
    "cd_expedidor_fiador_one" TEXT,
    "cd_expedidor_fiador_two" TEXT,
    "cd_profissao_fiador_one" DECIMAL,
    "cd_profissao_fiador_two" DECIMAL,
    "cd_tipo_logradouro_fiador_one" TEXT,
    "cd_tipo_logradouro_fiador_two" TEXT,
    "cep_fiador_one" TEXT,
    "cep_fiador_two" TEXT,
    "cis_fiador_one" TEXT NOT NULL,
    "cis_fiador_two" TEXT NOT NULL,
    "conta" TEXT,
    "ds_filicao_mae_fiador_one" TEXT,
    "ds_filicao_mae_fiador_two" TEXT,
    "ds_filicao_pai_fiador_one" TEXT,
    "ds_filicao_pai_fiador_two" TEXT,
    "ds_info_imovel_fiador" TEXT,
    "ds_info_imovel_fiador_one" TEXT,
    "ds_info_imovel_fiador_two" TEXT,
    "ds_naturalidade_fiador_one" TEXT,
    "ds_naturalidade_fiador_two" TEXT,
    "dt_cadastro_fiador_one" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "dt_cadastro_fiador_two" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "dt_nascimento_fiador_one" DATETIME,
    "dt_nascimento_fiador_two" DATETIME,
    "e_mail_fiador_one" TEXT,
    "e_mail_fiador_two" TEXT,
    "end_complemento_fiador_one" TEXT,
    "end_complemento_fiador_two" TEXT,
    "end_fiador_one" TEXT,
    "end_fiador_two" TEXT,
    "fornecedor" TEXT,
    "ie_fiador_one" TEXT,
    "ie_fiador_two" TEXT,
    "im_fiador_one" TEXT,
    "im_fiador_two" TEXT,
    "nm_fantasia_fiador_one" TEXT,
    "nm_fantasia_fiador_two" TEXT,
    "nm_fiador_one" TEXT,
    "nm_fiador_two" TEXT,
    "nu_celular_fiador_one" TEXT,
    "nu_celular_fiador_two" TEXT,
    "nu_endereco_fiador_one" TEXT,
    "nu_endereco_fiador_two" TEXT,
    "nu_fone_banco" TEXT,
    "nu_fone_fiador_one" TEXT,
    "nu_fone_fiador_two" TEXT,
    "nu_fone_fornecedor" TEXT,
    "nu_fone_zap_fiador_one" DECIMAL,
    "nu_fone_zap_fiador_two" DECIMAL,
    "obs_fiador_one" TEXT,
    "obs_fiador_two" TEXT,
    "rg_fiador_one" TEXT,
    "rg_fiador_two" TEXT,
    "tipo_fiador_one" TEXT,
    "tipo_fiador_two" TEXT,
    "vlr_salario_fiador_one" DECIMAL,
    "vlr_salario_fiador_two" DECIMAL,
    CONSTRAINT "Formulario_Pessoa_cd_escolaridade_fkey" FOREIGN KEY ("cd_escolaridade") REFERENCES "ESCOLARIDADE" ("cd_escolaridade") ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT "Formulario_Pessoa_cd_bairro_pessoa_fkey" FOREIGN KEY ("cd_bairro_pessoa") REFERENCES "Bairro" ("cd_bairro") ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT "Formulario_Pessoa_cd_cidade_pessoa_fkey" FOREIGN KEY ("cd_cidade_pessoa") REFERENCES "Cidade" ("cd_cidade") ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT "Formulario_Pessoa_cd_estado_civil_pessoa_fkey" FOREIGN KEY ("cd_estado_civil_pessoa") REFERENCES "Estado_Civil" ("cd_estado_civil") ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT "Formulario_Pessoa_cd_profissao_pessoa_fkey" FOREIGN KEY ("cd_profissao_pessoa") REFERENCES "Profissao" ("cd_profissao") ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT "Formulario_Pessoa_cd_tipo_logradouro_pessoa_fkey" FOREIGN KEY ("cd_tipo_logradouro_pessoa") REFERENCES "Tipo_Logradouro" ("cd_tipo_logradouro") ON DELETE NO ACTION ON UPDATE NO ACTION
);

-- CreateTable
CREATE TABLE "Profissao" (
    "cd_profissao" DECIMAL NOT NULL PRIMARY KEY,
    "ds_profissao" TEXT,
    "msrepl_synctran_ts" timestamp NOT NULL
);

-- CreateTable
CREATE TABLE "Tipo_Logradouro" (
    "cd_tipo_logradouro" TEXT NOT NULL PRIMARY KEY,
    "ds_tipo_logradouro" TEXT NOT NULL,
    "msrepl_synctran_ts" timestamp NOT NULL
);

-- CreateTable
CREATE TABLE "REFRESH_TOKEN" (
    "id" TEXT NOT NULL,
    "expiresIn" INTEGER NOT NULL,
    "user_id" TEXT NOT NULL,
    "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "REFRESH_TOKEN_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "USERS_APP" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "USERS_APP" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "email" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "users" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "cpf" TEXT NOT NULL,
    "telefone" TEXT NOT NULL,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_at" DATETIME
);

-- CreateIndex
CREATE UNIQUE INDEX "REFRESH_TOKEN_user_id_key" ON "REFRESH_TOKEN"("user_id");

-- CreateIndex
CREATE UNIQUE INDEX "USERS_APP_users_key" ON "USERS_APP"("users");

-- CreateIndex
CREATE UNIQUE INDEX "USERS_APP_cpf_key" ON "USERS_APP"("cpf");
